#!/bin/bash/env bash
# Check the no. of parameters
if [ $# -lt 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# Assign the parameters to variables
FILE=$1
IP=$2
USER=$3
KEY=$4

# Transfer the file to user home directory on the server
scp -i $KEY -o StrictHostKeyChecking=no $FILE $USER@$IP:~/

