#!/usr/bin/env bash
# Commands to install Nginx on Web-Sever-01,

# Updating Packages before Installations,
sudo apt-get update
sudo apt-get -y install nginx

# Config Uncomplicated Firewall (UFW) to allow incoming traffic for Nginx HTTP service,
sudo ufw allow 'Nginx HTTP'

# Create an index.html page,
echo "Hello World!" | sudo tee /var/www/html/index.html

# Test Nginx config. for Syntax errors,
sudo nginx -t

# Restart the Nginx.
sudo service nginx start

