#!/usr/bin/env bash
#  Script to config. a new Ubuntu machine to Perform a 301-redirection,

# script to Upadate Packages before Installations,
sudo apt-get update
sudo apt-get install -y nginx

# Create an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Perform a 301 Redirection,
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/besthor permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Restart Nginx service,
sudo service nginx restart


# Install Nginx
apt update
apt install -y nginx

# Replace a line with multiple lines with sed
echo 'sed "/foo/ { N; s/foo\\n.*/bar\\nbaz\\nqux/ }" file.txt' > sed_script.sh

# Configure Nginx to redirect /redirect_me
echo 'server {
  . . .
  location = /redirect_me {
    return 301 $scheme://www.youtube.com/watch?v=QH2-TGUlwu4$request_uri;
  }
  . . .
}' > /etc/nginx/sites-available/default

# Reload Nginx
systemctl reload nginx


server {
  . . .
  location = /redirect_me {
    return 301 $scheme://www.youtube.com/watch?v=QH2-TGUlwu4$request_uri;
  }
  . . .
}


sed '/foo/ { N; s/foo\\n.*/bar\\nbaz\\nqux/ }' file.txt

