#!/usr/bin/env bash
#-f added to task 0 to forcefully rids the file if it exists,,
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
sed -i 's/listen  .*/listen 80;/' /etc/nginx/sites-available/default
service nginx reload

