#!/usr/bin/env bash
# Configures and ensures Nginx server to listen on port 80with slight changes.
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)”

