#!/usr/bin/env bash
# Displays "Best School" 10 times using while loop
# displays "Hi" On the 9th iteration, before Displaying "Best School"

count=0

while [ $count -lt 10 ]
do
	if [ $count -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	(( count++ ))
done
