#!/usr/bin/env bash
# This script changes the localhost IP to 127.0.0.2 and the facebook.com IP to 8.8.8.8 in the /etc/hosts file

# Use sed to replace the localhost IP with 127.0.0.2 and append the facebook.com IP to the /etc/hosts file
# Use the -b option to make a backup of the original file
sed -i.bak -e 's/127.0.0.1/127.0.0.2/' -e '$a8.8.8.8 facebook.com' /etc/hosts | tee /etc/hosts

# Restart the networking service to apply the changes
systemctl restart networking

