#!/usr/bin/env bash
# This script changes the localhost IP to 127.0.0.2 
# and facebook.com IP to 8.8.8.8 in the /etc/hosts file
# Make a backup of the original /etc/hosts file
# Use sed to replace the localhost IP with 127.0.0.2
# Use echo to append the facebook.com IP to the /etc/hosts file
# Restart the networking service to apply the changes
# Restart the networking service to apply the changes

$cp /etc/hosts /etc/hosts.bak

$sed -i 's/127.0.0.1/127.0.0.2/' /etc/hosts

$echo "8.8.8.8 facebook.com" >> /etc/hosts

$service networking restart
