#!/usr/bin/env bash
# This script changes the localhost IP to 127.0.0.2 and the facebook.com IP to 8.8.8.8 in the /etc/hosts file
# Use sed to replace the localhost IP with 127.0.0.2 and append the facebook.com IP to the /etc/hosts file

cp /etc/hosts ~/hosts.new
echo "127.0.0.2		localhost" > ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
