#!/usr/bin/env bash
# Fixes web server to run Nginx as nginx user listening on port 8080,

# set a user in config by replace '#user' and it's value,
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
# replaces port 80 with 8080 in sites-available config,
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
# gives owner permissions to read and write to config file,
chmod 644 /etc/nginx/nginx.conf
# apache may interfere with nginx so kill process if it is running,
pkill apache2
# now start nginx service with new nginx user,
sudo -u nginx service nginx start
